#!/bin/bash

SERVICE=birdseye

echo "[i] Post install $SERVICE"
echo "[i] Creating user and updating permissions"
useradd --system -d /opt/ecix/$SERVICE $SERVICE

# Initialize venv
cd /opt/ecix/$SERVICE && ./bin/venv_init

echo "[i] Clearing bytecode cache files"
find /opt/ecix/$SERVICE -name "*.pyc" -exec rm {} \;
find /opt/ecix/$SERVICE -name "__pycache__" -exec rm -fr {} \;


SERVICE_STATUS=$(status $SERVICE)
if [[ $SERVICE_STATUS == *"stop"* ]] 
then 
        echo "[i] Remember to start the $SERVICE server!"
        echo "# start $SERVICE"
else
        echo "[i] Restarting birdseye server..."
        /sbin/restart $SERVICE
fi

